# Generated by Django 5.2.4 on 2025-08-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='media_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
